### PR TITLE
fix bad root-scopes initialisation

### LINKED ISSUE #713: Write into Public CTIA by a JWT token
Currently, we can POST any types of entity (a sighting for example) into public CTIA using a JWT token, like a token from the local storage in the browser.
I thought we can write into CTIA using API_KEY only. 
Is it an issue or by design?

@folbricht @craigbro @gbuisson @saintx

### PR DESCRIPTION
**Pull request by yogsototh**
Close #713 
Close https://github.com/threatgrid/iroh/issues/1949

Root scopes properties wasn't correctly set due to bad init ordering.

_We should think about using TK or a similar project to handle init order and prevent future errors like these._

### CODE REVIEW

File: test/ctia/auth/jwt_test.clj [hunk 1]
```diff
@@ -33,45 +40,45 @@
 
 
 (deftest scopes-to-capapbilities-test
-  (is (= "private-intel" sut/entity-root-scope)
+  (is (= "private-intel" @sut/entity-root-scope)
```
Comment (gbuisson) [inline test/ctia/auth/jwt_test.clj]: setting default properties configuration should be done on `ctia-default.properties` and not hardcoded, doing this will make this test useless.

File: src/ctia/auth/jwt.clj [hunk 2]
```diff
@@ -10,13 +10,19 @@
     [auth :as auth :refer [IIdentity]]
     [properties :as prop]]))
 
-(def entity-root-scope
-  (get-in @prop/properties [:ctia :auth :entities :scope]
-          "private-intel"))
+(def entity-root-scope (atom nil))
```
Comment (gbuisson) [inline src/ctia/auth/jwt.clj]: I would much prefer if we change the `def` to `defn` instead of creating an atom just for that
