### PR TITLE
Resolving depencency overrides

### LINKED ISSUE #411: Swagger.json route throws an exception
On master branch, swagger-ui interface doesn't load as the swagger.json route fails.

the full exception is:

~~~
2016-08-25 19:10:18,867 ERROR (qtp925800237-34 - /swagger.json) [ctia.http.exceptions] - schema.core.Maybe cannot be cast to clojure.lang.IFn
java.lang.ClassCastException: schema.core.Maybe cannot be cast to clojure.lang.IFn
	at schema_tools.walk$walk.invokeStatic(walk.cljc:33)
	at schema_tools.walk$walk.invoke(walk.cljc:17)
	at ring.swagger.core$name_schemas.invokeStatic(core.clj:66)
	at ring.swagger.core$name_schemas.invoke(core.clj:65)
	at ring.swagger.core$with_named_sub_schemas.invokeStatic(core.clj:91)
	at ring.swagger.core$with_named_sub_schemas.invoke(core.clj:84)
	at ring.swagger.swagger2$ensure_response_sub_schemas$fn__37330$fn__37331.invoke(swagger2.clj:141)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$update_in.invokeStatic(core.clj:5950)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$update_in.invokeStatic(core.clj:5949)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$update_in.invokeStatic(core.clj:5949)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at ring.swagger.swagger2$ensure_response_sub_schemas$fn__37330.invoke(swagger2.clj:141)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at ring.swagger.swagger2$ensure_response_sub_schemas.invokeStatic(swagger2.clj:140)
	at ring.swagger.swagger2$ensure_response_sub_schemas.invoke(swagger2.clj:135)
	at ring.swagger.swagger2$transform_operations$iter__37336__37342$fn__37343$iter__37338__37345$fn__37346.invoke(swagger2.clj:161)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$concat$fn__4446.invoke(core.clj:706)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$reduce.invoke(core.clj:6527)
	at ring.swagger.swagger2$transform_operations.invokeStatic(swagger2.clj:163)
	at ring.swagger.swagger2$transform_operations.invoke(swagger2.clj:154)
	at ring.swagger.swagger2$ensure_body_and_response_schema_names.invokeStatic(swagger2.clj:176)
	at ring.swagger.swagger2$ensure_body_and_response_schema_names.invoke(swagger2.clj:169)
	at ring.swagger.swagger2$fn__37379$swagger_json__37388$fn__37391.invoke(swagger2.clj:233)
	at ring.swagger.swagger2$fn__37379$swagger_json__37388.invoke(swagger2.clj:203)
	at compojure.api.swagger$swagger_docs$fn__37421.invoke(swagger.clj:66)
	at compojure.core$make_route$fn__35671.invoke(core.clj:130)
	at compojure.core$wrap_route_middleware$fn__35667.invoke(core.clj:118)
	at compojure.core$if_route$fn__35643.invoke(core.clj:41)
	at compojure.core$if_method$fn__35635.invoke(core.clj:27)
	at compojure.api.routes.Route.invoke(routes.clj:58)
	at compojure.api.core$ring_handler$fn__37081$fn__37082.invoke(core.clj:11)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.api.core$ring_handler$fn__37081.invoke(core.clj:11)
	at compojure.api.routes.Route.invoke(routes.clj:58)
	at compojure.api.core$ring_handler$fn__37081$fn__37082.invoke(core.clj:11)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.api.core$ring_handler$fn__37081.invoke(core.clj:11)
	at compojure.api.routes.Route.invoke(routes.clj:58)
	at ring.swagger.middleware$wrap_swagger_data$fn__36691.invoke(middleware.clj:33)
	at ring.middleware.http_response$wrap_http_response$fn__36552.invoke(http_response.clj:8)
	at ring.swagger.middleware$wrap_swagger_data$fn__36691.invoke(middleware.clj:33)
	at compojure.api.middleware$wrap_options$fn__36737.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__36316.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__36316.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__36316.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__36316.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__36316.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__36727.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__36462.invoke(format_response.clj:183)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__36582.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__36626.invoke(nested_params.clj:84)
	at ring.middleware.params$wrap_params$fn__36682.invoke(params.clj:64)
	at compojure.api.middleware$wrap_options$fn__36737.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:58)
	at clojure.lang.Var.invoke(Var.java:379)
	at ring.adapter.jetty$proxy_handler$fn__40216.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
~~~

### PR DESCRIPTION
**Pull request by polygloton**
Closes #411

### CODE REVIEW

**Comment by gbuisson** [comment]
LGTM

File: src/ctia/http/routes/bulk.clj [hunk 1]
```diff
@@ -129,7 +129,7 @@
       :identity login
       (if (> (bulk-size bulk) (get-bulk-max-size))
         (bad-request (str "Bulk max nb of entities: " (get-bulk-max-size)))
-        (created (gen-bulk-from-fn create-entities bulk login))))
+        (created nil (gen-bulk-from-fn create-entities bulk login))))
```
Comment (yogsototh) [inline src/ctia/http/routes/bulk.clj]: Should use the `common` created.

**Comment by yogsototh** [comment]
Except from my comment LGTM!
