### PR TITLE
Resolved identified todo's from redis work

### LINKED ISSUE #255: TODOs for redis pubsub
These are follow-up tasks related to #23 

- [x] Use core.async/thread for blocking IO instead of green threads.  (For example ctia.lib.async/register-listener could take a 'type that allows :compute or :blocking, much like core.async/pipeline does).
- [x] Refactor ctia.lib.async to not know what an Event is.  Might be able to just change the terminology from Event to Entity.
- [ ] Handle exceptions in core.async go/thread blocks.  Don't want exceptions to be swallowed or allow it to kill threads.
- [x] Resolve: What is a redis store?
  - A redis store should not be a thing
- [x] Use hooks to publish redis events
- [x] No need to support subscribing to events (except for testing of course)

### PR DESCRIPTION
**Pull request by polygloton**
- Ns "lib.async" no longer refers to events
- May use a real thread when registering a listener

Closes #255

### CODE REVIEW

File: src/ctia/lib/async.clj [hunk 1]
```diff
@@ -63,28 +77,40 @@
...
+               :listener-fn listener-fn
+               :events events
+               :end-chan end-chan)
+
+       :compute
+       (listen :mode :compute
+               :pred pred
+               :listener-fn listener-fn
+               :events events
+               :end-chan end-chan))
```
Comment (yogsototh) [inline src/ctia/lib/async.clj]: I might forgot something here, but why a case?
Why not:

~~~ clojure
(listen :mode mode
    :pred pred
    :listener-fn listener-fn
    :events events
    :end-chan end-chan)
~~~

**Comment by yogsototh** [comment]
Except from my remark sounds good to me.

File: src/ctia/lib/async.clj (hunk 1 above)
Comment (polygloton) [inline src/ctia/lib/async.clj]: Since listen is a macro, it needs to be passed the mode at compile time.  It subtle.  :)

**Comment by gbuisson** [comment]
sounds good!
