### PR TITLE
fixed issues related to latest CTIM version

### LINKED ISSUE #394: ES mapping is incorrect
Our current tests are passing because we don't generate optional keys on schema generative tests.

- Update CTIM so that optional keys are generated
- Fix CTIA/CTIM related issues

### PR DESCRIPTION
**Pull request by gbuisson**
depends on https://github.com/threatgrid/ctim/pull/31
closes #394 

- updated ES mapping with missing fields
- small fixes linked to latest CTIM version

### CODE REVIEW

File: src/ctia/stores/es/mapping.clj [hunk 1]
```diff
@@ -609,3 +668,6 @@
          exploit-target-mapping
          sighting-mapping
          identity-mapping))
+
+
+(keys  incident-mapping)
```
Comment (yogsototh) [inline src/ctia/stores/es/mapping.clj]: I believe this is a forgotten call for local testing. This should be removed.

Comment (gbuisson) [inline src/ctia/stores/es/mapping.clj]: oops!

**Comment by yogsototh** [comment]
LGTM!
