### PR TITLE
Fix diff between bundle and bulk keys

### LINKED ISSUE #659: Attack patterns are no longer imported by the bundle importer

### PR DESCRIPTION
**Pull request by msprunck**
Closes #659

Bundle keys are used by the bundle importer to:
- identify entity types
  Ex: `attack_patterns` -> `:attack-pattern`

This PR updates the way entity types are resolved from bundle keys.

### CODE REVIEW

File: test/ctia/http/routes/bundle_test.clj [hunk 1]
```diff
@@ -159,6 +194,17 @@
                            (range)
                            indicators
                            sightings)]
+    (testing "Import bundle with all entity types"
+      (let [new-bundle (deep-dissoc bundle-maximal :id)
```
Comment (gbuisson) [inline test/ctia/http/routes/bundle_test.clj]: haha!

File: test/ctia/http/routes/bundle_test.clj [hunk 2]
```diff
@@ -143,6 +145,39 @@
   [entity]
   (update entity :description str "-modified"))
 
+(defn deep-dissoc
```
Comment (gbuisson) [inline test/ctia/http/routes/bundle_test.clj]: it could be useful to deport that into some utility library/ns

**Comment by hshahman** [comment]
No QA required.
