### PR TITLE
Resolve transient IDs for the bulk POST route

### LINKED ISSUE #610: Transient Ids are not converted into full ids
when using the bulk API, one can use transient ids on records of the bundle.
The bulk API is supposed to generate *real* ids from them but that doesn't happen,
instead records are created straight with the set transient id:

```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 100,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "v0.4.16_ctia_actor",
        "_type" : "actor",
        "_id" : "transient:10b9abd5-1b71-41ca-9c0e-4375a259f7db",
        "_score" : 1.0,
        "_source" : {
          "valid_time" : {
            "end_time" : "2525-01-01T00:00:00.000Z",
            "start_time" : "2017-10-18T10:47:43.939Z"
          },
          "schema_version" : "0.4.16",
          "type" : "actor",
          "created" : "2017-10-18T10:47:43.939Z",
          "source" : "a source",
          "modified" : "2017-10-18T10:47:43.939Z",
          "actor_type" : "Hacker",
          "id" : "transient:10b9abd5-1b71-41ca-9c0e-4375a259f7db",
          "tlp" : "green",
          "groups" : [
            "Administrators"
          ],
          "confidence" : "High",
          "owner" : "Unknown"
        }
      },
      {
        "_index" : "v0.4.16_ctia_actor",
        "_type" : "actor",
        "_id" : "transient:116a87ca-f2e1-46ef-aedb-ef8f77e32dcc",
        "_score" : 1.0,
        "_source" : {
          "valid_time" : {
            "end_time" : "2525-01-01T00:00:00.000Z",
            "start_time" : "2017-10-18T10:47:43.953Z"
          },
          "schema_version" : "0.4.16",
          "type" : "actor",
          "created" : "2017-10-18T10:47:43.953Z",
          "source" : "a source",
          "modified" : "2017-10-18T10:47:43.953Z",
          "actor_type" : "Hacker",
          "id" : "transient:116a87ca-f2e1-46ef-aedb-ef8f77e32dcc",
          "tlp" : "green",
          "groups" : [
            "Administrators"
          ],
          "confidence" : "High",
          "owner" : "Unknown"
        }
      },
```

### PR DESCRIPTION
**Pull request by msprunck**
Closes #610 

It is now possible to create entities with relationships in a single POST request. 

Ex: 
```clojure
{:sightings
 [{:id "transient:f48a3768-07d6-46c9-bc8d-ff2093d10826"
   :title "sighting-title"
   :observed_time {:start_time #inst "2016-02-11T00:40:48.212-00:00"
                   :end_time #inst "2016-02-11T00:40:48.212-00:00"}
   :confidence "High"
   :count 1}]
 :indicators
 [{:id "transient:41c4ebba-241a-4e2a-b17f-feb90897f614"
   :title "indicator-title"
   :producer "producer"
   :valid_time {}}]
 :relationships
 [{:relationship_type "indicates"
   :source_ref "transient:41c4ebba-241a-4e2a-b17f-feb90897f614"
   :target_ref "transient:f48a3768-07d6-46c9-bc8d-ff2093d10826"}]}
```

The route `POST /ctia/bulk` will:
- Create the sighting
- Create the indicator
- Converts all transient IDs in the relationship and create the entity
- Return a `BulkRefs` with all new IDs and a `:tempids` field which contains the mapping table between transient and real IDs

Response:

```clojure
{:indicators
 ["http://example.com/ctia/indicator/indicator-991d8dfb-b54e-4435-ac58-2297b4d886c1"]
 :sightings
 ["http://example.com/ctia/sighting/sighting-71205a63-a9f3-4576-b2a1-3179587dbaa9"]
 :relationships
 ["http://example.com/ctia/relationship/relationship-5ab99ba5-ce4f-4c51-9f3e-8916d1665a4b"]
 :tempids
 {"transient:41c4ebba-241a-4e2a-b17f-feb90897f614"
  "http://example.com/ctia/indicator/indicator-991d8dfb-b54e-4435-ac58-2297b4d886c1"
  "transient:f48a3768-07d6-46c9-bc8d-ff2093d10826"
  "http://example.com/ctia/sighting/sighting-71205a63-a9f3-4576-b2a1-3179587dbaa9"}}
```

### CODE REVIEW

**Comment by saintx** [comment]
This isn't supposed to replace the current `/bulk` API endpoint.  It's supposed to add a new `/bundle` API endpoint, so that we can restrict its use via permissions until we are confident in how it works.  Craig placed a lot of emphasis on that requirement.

Otherwise, this looks very promising!

**Comment by msprunck** [comment]
This is still the `/ctia/bulk` API. This PR fixes the issue #610.

**Comment by gbuisson** [comment]
@saintx, it's a bug involving the bulk route, eventually I believe parts of the bulk route code will be used for the bundle import so we had to fix that first.

**Comment by saintx** [comment]
Sounds good, then!

File: src/ctia/http/routes/bulk.clj [hunk 1]
```diff
@@ -149,6 +153,60 @@
...
+    transientid3 id3
+    transientid4 id4}
+
+  The create-entities set the enveloped-result? to True in the flow
+  configuration to get :data and :tempids for each entity in the result."
+  [entities]
+  (reduce (fn [acc [_ v]]
+            (into acc (:tempids v)))
+          {}
+          entities))
```
Comment (yogsototh) [inline src/ctia/http/routes/bulk.clj]: Why not:

~~~
(->> entities
     (map (fn [_ v] (:tempids v))
     (reduce into {}))
~~~
