### PR TITLE
Fixed Redis on CI

### LINKED ISSUE #256: Resolve redis issues on travis
For #23, we had trouble getting tests to pass on CI, even though they passed locally.  There is a test marked :disabled, which was failing because Redis on CI didn't publish to the subscribed channel.

### PR DESCRIPTION
**Pull request by polygloton**
- Adding environment tests for redis that may trigger when redis doesn't work
- Will fix redis in CI
- Will do some refactoring as I go

Fixes #256

### CODE REVIEW

**Comment by polygloton** [comment]
Here is what I did to fix the issue.  I added a test that worked out pub/sub directly with carmine, doing some refactoring along the way to make it easier.  Though I confused myself at first by misinterpreting the results, it proved that redis was working correctly on CI.  Then I cleaned up the way that state is managed, especially in how it was being fixtures in the tests.  Things still failed until I realized that we were overriding the REDIS_ENABLED var in the travis config.  I believe that the reason tests were failing was due to state management and that flag causing havoc.  Why did it pass locally but not on CI?  I'm not entirely sure, but I suspect there was a difference in the order or tests being run.  In the end it doesn't matter; the state management code is better in this PR and tests are passing.

File: src/ctia/lib/redis.clj [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+  (c/with-open-listener pubsub-listener
+    (c/unsubscribe)))
+
+(defn subscribe [host-port event-channel-name listener-fn]
+  (c/with-new-pubsub-listener (:spec (server-connection host-port))
+    {event-channel-name listener-fn}
+    (c/subscribe event-channel-name)))
+
+(defn publish [host-port event-chanel-name event]
+  (c/wcar (server-connection host-port)
```
Comment (polygloton) [inline src/ctia/lib/redis.clj]: Rebuilding the server-connection map each time we publish is inefficient, but I will resolve that in issue #255

**Comment by polygloton** [comment]
I also changed the way that ENV vars are defined in travis so that there is one per line.  This should make it much easier to verify.
